### PR TITLE
Added DetectIntelGPU function

### PR DESCRIPTION
**Pull request by DmitryHetman**
This function detects integrated GPU based on cpu model.

### CODE REVIEW

**Comment by DmitryHetman** [comment]
Merge it.

**Comment by darealshinji** [comment]
Please don't be so bossy. I will merge it before I tag a new release. But can you please fix the indentation a bit first?

**Comment by DmitryHetman** [comment]
Yes I can.

**Comment by DmitryHetman** [comment]
What exactly do you want me to fix?

**Comment by darealshinji** [comment]
I just wanted the indentation to be more like the rest of the script, but I did that myself: https://github.com/KittyKatt/screenFetch/commit/0496a0e2a56bfc6eb1f540fc24dcdaa764b577a0

**Pull request merged**
