### PR TITLE
fix shell detection on (gentoo) musl-libc linux distros

### PR DESCRIPTION
**Pull request by parazyd**

### CODE REVIEW

**Comment by darealshinji** [comment]
Why not like this?

``` diff
@@ -658,7 +658,7 @@ detectdistro () {
 			fi
 
 			if [[ "${distro}" == "Unknown" ]]; then
-				if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux" ]]; then
+				if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux-musl" || "${OSTYPE}" == "linux" ]]; then
 					if [ -f /etc/lsb-release ]; then
 						LSB_RELEASE=$(</etc/lsb-release)
 						distro=$(echo ${LSB_RELEASE} | awk 'BEGIN {
@@ -685,7 +685,7 @@ detectdistro () {
 			fi
 
 			if [[ "${distro}" == "Unknown" ]]; then
-				if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "gnu" ]]; then
+				if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux-musl" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "gnu" ]]; then
 					if [ -f /etc/arch-release ]; then distro="Arch Linux"
 					elif [ -f /etc/chakra-release ]; then distro="Chakra"
 					elif [ -f /etc/crunchbang-lsb-release ]; then distro="CrunchBang"
@@ -802,7 +802,7 @@ detectdistro () {
 				fi
 			fi
 
-			if [[ "${distro}" == "Unknown" ]] && [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "gnu" ]]; then
+			if [[ "${distro}" == "Unknown" ]] && [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux-musl" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "gnu" ]]; then
 				if [[ -f /etc/issue ]]; then
 					distro=$(awk 'BEGIN {
 						distro = "Unknown"
@@ -830,7 +830,7 @@ detectdistro () {
 				fi
 			fi
 
-			if [[ "${distro}" == "Unknown" ]] && [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "gnu" ]]; then
+			if [[ "${distro}" == "Unknown" ]] && [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux-musl" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "gnu" ]]; then
 				if [[ -f /etc/system-release ]]; then
 					if grep -q "Scientific Linux" /etc/system-release; then
 						distro="Scientific Linux"
@@ -1434,7 +1434,7 @@ detectshell () {
 				shell_type=$(echo "$SHELL" | awk -F'/' '{print $NF}')
 			fi
 		else
-			if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux" ]]; then
+			if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux-musl" || "${OSTYPE}" == "linux" ]]; then
 				shell_type=$(ps -p $PPID -o cmd --no-heading)
 			elif [[ "${distro}" == "Mac OS X" || "${distro}" == "DragonFlyBSD" || "${distro}" == "FreeBSD" || "${distro}" == "OpenBSD" || "${distro}" == "NetBSD" ]]; then
 				shell_type=$(ps -p $PPID -o command | tail -1)
```

**Comment by parazyd** [comment]
well, neither *BSD, nor Mac OS X, nor Scientific Linux, nor CrunchBang, nor Chakra, nor Arch (will) use musl-libc so I don't see the reason to add the "linux-musl" check everywhere.

**Comment by darealshinji** [comment]
Good point, but why not add the check to line 1437 instead of 1428?

**Comment by parazyd** [comment]
Very well, rebased.

**Pull request merged**
