### PR TITLE
Add support for ALDOS.

### PR DESCRIPTION
**Pull request by darkshram**
Add support for ALDOS.

### CODE REVIEW

**Comment by darealshinji** [comment]
What package manager is it using? Can you also provide a screenshot of screenfetch's output on this distro?

**Comment by darkshram** [comment]
It uses rpm. 
pantallazo-2017-09-30 11-55-26

**Comment by darkshram** [comment]
This is the original logo.
aldos

**Comment by darealshinji** [comment]
It doesn't show any OS version. Is it a rolling release distro?

**Comment by darkshram** [comment]
Yes, currently is rolling release, but yes, it should show the release version. Which line should I modify?

**Comment by darealshinji** [comment]
What's the output of `lsb_release -sirc`?

**Comment by darkshram** [comment]
ALDOS 1.4.12 Activism

**Comment by darealshinji** [comment]
Change this part:
``` sh
"ALDOS"|"Aldos")
	distro="ALDOS"
	distro_codename="n/a"
	distro_release="n/a"
```
to this:
``` sh
"ALDOS"|"Aldos")
	distro="ALDOS"
```
and see if it now shows release and codename.

**Comment by darkshram** [comment]
Done. Thnak you!
screenfetch-aldos

**Pull request merged**
