### PR TITLE
PCLinuxOS detection

### PR DESCRIPTION
**Pull request by darealshinji**
PCLinuxOS is a user-friendly rolling-release distribution.
There's no logo because I'm unsure what the official distro logo actually is.

### CODE REVIEW

**Comment by KittyKatt** [comment]
Lots of merge conflicts...gonna have to figure out how to merge this.

**Comment by darealshinji** [comment]
I could make a new PR if you prefer that.

**Comment by KittyKatt** [comment]
Tha would be prefered. I need to learn how to do merges better through conflicts.

**Comment by darealshinji** [comment]
https://github.com/KittyKatt/screenFetch/pull/272

**Pull request closed without merging**
