### PR TITLE
unify  [ -f /etc/${distro}-release ]

### PR DESCRIPTION
**Pull request by konfou**
Names will be in lowercase but in current code they will be fixed anyway later on. Next interesting step will be dropping the `for` loop entirely and just checking if there is a file `/etc/<something>-release` and `setting distro=<something>`.

### CODE REVIEW

**Comment by darealshinji** [comment]
Can you re-add `distro="Red Star OS"` to the `"${distro}" == "redstar" ` part, because IIRC the default distro name was in Korean.

I agree that this part could probably be simplified, however I wouldn't just blindly assume the distro to be `DIST` if a file `/etc/DIST-release` exists. Think of all the distros that for example have `/etc/redhat-release` and aren't RHEL.

**Comment by konfou** [comment]
It isn't needed as it is in `case $distro`statement. `distro` will be set to redstar and then to 'Red Star OS' inside it. Yes, a DIST-release doesn't mean distro is DIST. The if statements following will make any corrections needed as in #! where the file is crunchbang-lsb.

**Comment by darealshinji** [comment]
One more question: have you tried this on a few distros?

**Comment by konfou** [comment]
True, some fixes were needed. Seems fine now.

**Pull request merged**
