### PR TITLE
Fixes for macOS

### PR DESCRIPTION
**Pull request by Albatrosicks**
commits 9cfe587, bb58b90 are for #620 
41b98a1 is for #646 
8c6f4c4 is for #663

### CODE REVIEW

**Comment by jhelfman** [comment]
I wouldn't suggest the package counting was fixed in this request, as doing an "ls" of a directory is by no means an accurate way to determine the package count on a system. I'm not suggesting there isn't a more accurate way, but this isn't the way to solve this issue. What if a package is unsuccessfully removed, or not cleaned up properly and the user doesn't remove the directory under the directory the count is being done on?

**Comment by Albatrosicks** [comment]
Actually brew does [same thing](https://github.com/Homebrew/brew/blob/2749c52d3f1ad34bd4c686fc4847b80e36a57a42/Library/Homebrew/cmd/list.rb#L73). 

```
$ brew list -v
ls /usr/local/Cellar
...
```

**Comment by jhelfman** [comment]
> Actually brew does [same thing](https://github.com/Homebrew/brew/blob/2749c52d3f1ad34bd4c686fc4847b80e36a57a42/Library/Homebrew/cmd/list.rb#L73) but slower.
> 
> ```
> $ brew list -v
> ls /usr/local/Cellar
> ...
> ```

Ok :) Perhaps, that is how it is managed. As a package maintainer, myself, that is scary!

**Comment by darealshinji** [comment]
Well, if Brew does the same...

**Pull request merged**
