### PR TITLE
Add Kogaion Linux Logo

### PR DESCRIPTION
**Pull request by crismblog**
Add Kogaion Linux Logo

### CODE REVIEW

**Comment by darealshinji** [comment]
If anyone wants a cleaner diff: https://github.com/darealshinji/screenFetch/commit/3d9e50dd932fc726040f84fa34023f900c1e9c0d

**Comment by crismblog** [comment]
Logo with three color is for Rogentos Groups.
and
Logo with blue color is for Kogaion distro.

**Comment by darealshinji** [comment]
Where's the homepage for Kogaion? When I search for it I only find Rogentos Group with the Romanian flag colored logo.

**Comment by crismblog** [comment]
Look http://www.zimagez.com/zimage/capturdeecran2016-05-0515-55-27.php

**Comment by darealshinji** [comment]
I see. Rogentos Group appearing everywhere on Google was really confusing. Anyway, I think you should rebase your pull request or make a new one (I don't want to criticize you, I just want to help this distro to be added very soon).
Here's a new diff from me that might help: https://github.com/darealshinji/screenFetch/commit/408972b38dddd7526780635be696e35b8dc84699
The logo is a little tweaked and I've changed the color to 'light blue' which I think looks better.

kogaion

**Comment by crismblog** [comment]
Looks very good. Thank you for everything you've done.

**Comment by darealshinji** [comment]
Changes added manually with https://github.com/KittyKatt/screenFetch/pull/348

**Pull request closed without merging**
