### PR TITLE
resolve issue #456

### PR DESCRIPTION
**Pull request by markscsmith**
Move test for busybox to after other detections (resolve issue #456 : readlink: illegal option -- f)

### CODE REVIEW

**Comment by darealshinji** [comment]
But this way the busybox test will never be done if your OS is Linux.

**Comment by tntc** [comment]
I may be confused about the purpose of the BusyBox test in the first place... BusyBox uses ash as its shell which currently returns a correct response (ash) when screenfetch is run

screen shot 2017-04-02 at 9 59 23 pm

except on tinyCore, which returns the alternative (but still valid) sh

screen shot 2017-04-02 at 10 14 49 pm

To get a shell from BusyBox, you either call `busybox ash` or `busybox sh`

I guess I'm saying I don't think BusyBox is technically a shell on its own, but rather _includes_ the ash/sh shell.  

However - whether I am correct or not - **user experience trumps all of this.** If you think users would expect to see busybox rather than ash/sh, I totally get that.  If you would rather have busybox show up over ash in the case that it really is a busybox instance, I could look for a more compatible way that will work on any of the distros.

For example something as simple as `ls -ls $SHELL | grep busybox` would properly detect BusyBox and work on any platform I can think of in that list.

**Comment by tntc** [comment]
I missed something else: TinyCore - the original target for this whole readlink condition - no longer reports BusyBox in any of the cases: it falls into the conditional [here](https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L1492) where screenfetch checks `"${distro}" == "TinyCore"` and then simply uses `shell_type=$(echo "$SHELL" | awk -F'/' '{print $NF}')` to get the "sh" result in my example above.

I'll try to throw together a branch that returns busybox as well, just for fun :)

**Comment by tntc** [comment]
OK. See branch [https://github.com/tntc/screenFetch/tree/busybox_checklinux](busybox_checklinux) (I named it poorly. Really it should work on any system that has BusyBox).  This uses the ls -ls trick I mentioned before.

    		if [[ $(ls -ls ${SHELL} | grep busybox) ]]; then
            	shell_type="BusyBox"
            fi

**Comment by darealshinji** [comment]
>I guess I'm saying I don't think BusyBox is technically a shell on its own, but rather includes the ash/sh shell. I think the check for BusyBox might not even be needed.

Sounds reasonable.

**Comment by tntc** [comment]
Well, now you have both of the options! :) Thanks @darealshinji!

**Comment by k4k** [comment]
@tntc Can you test if the following would work? `readlink` without any flags returns consistent output across the various platforms I tested and is cleaner than parsing `ls -ls`.

```
readlink "${SHELL}" | grep -q busybox && shell_type="BusyBox"
```

**Comment by tntc** [comment]
@k4k your version seems to work fine on macOS, though I can't swear to it working on other platforms for the intended purpose.  It's interesting: TinyCore was the original target for this code in the first place, but now it'll never run on TinyCore because of the conditional above.  I think this entire chunk of code could be snipped out and it would report the shell as sh/ash, both of which are valid.

**Comment by liwakura** [comment]
@markscsmith Busybox also has another shell beside ash, namely hush. Also, they might either be invoked directly as `ash` or `busybox ash`. I choose to display BusyBox in this case because its the thing the release version "belongs to".

Support for TinyCore Linux was not removed, but it was generalized in a way that the BusyBox check would match all busybox-based distros (Alpine, TinyCore, Sabotage, my own shit).

My fault was just not knowing that readlink -F is not portable.

#460 is problematic because the code wont be able to be reached at its new location, since BusyBox-based distributions will get handled by `"${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "linux" || "${OSTYPE}" == "linux-musl"`

The correct fix would be `stat` or redirecting `readlink`'s stderr to /dev/null.

**Comment by stek29** [comment]
Why won't just adding `2>&1` after readlink work?
On the systems with busybox you'll have busybox's readlink which supports `-f` option
On bsd binutils `readlink -f` won't work, but have you ever seen busybox shell with bsd binutils?

**Comment by stek29** [comment]
I guess #494 fixed this :)

**Pull request closed without merging**
