### PR TITLE
new distro: NixOS

### PR DESCRIPTION
**Pull request by darealshinji**
http://nixos.org/

I had to do this hackery at `detectres()` to prevent warnings about xdpyinfo not being found.

nixos

### CODE REVIEW

**Comment by KittyKatt** [comment]
Oh dear, that is pretty hacky. I'll look through it and see what I can do about it, perhaps. If I can't figure out a better way, I'll just merge it. Thanks again!

**Comment by KittyKatt** [comment]
Hey, @darealshinji you ever get on IRC?

**Comment by darealshinji** [comment]
It looks like xdpyinfo is listed among the runtime dependencies for the official package so the part at `detectres()` can probably be reverted: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/screenfetch/default.nix

**Comment by darealshinji** [comment]
I will make a new PR.

**Pull request closed without merging**
