### PR TITLE
Add GPU detection for FreeBSD with nvidia-settings installed

### PR DESCRIPTION
**Pull request by distcoll**
Added a check for if nvidia-settings is installed on FreeBSD. If it is, then use it to detect the name of the GPU.

### CODE REVIEW

**Comment by dylanaraps** [comment]
What does the output look like?

**Comment by distcoll** [comment]
It comes out as:
GPU: GeForce GTX 950

**Comment by dylanaraps** [comment]
Thanks!

What does this output exactly?

```sh
nvidia-settings -t -q gpus
```

**Comment by distcoll** [comment]
```
1 GPU on stellator:0

    [0] stellator:0[gpu:0] (GeForce GTX 950)

      Has the following names:
        GPU-0
        GPU-148b64de-eee6-cf7c-566e-7040ccf044f1
```

The grep and sed are to isolate the bit between the parentheses.

**Comment by dylanaraps** [comment]
Thanks!

**Comment by darealshinji** [comment]
Changes added manually with https://github.com/KittyKatt/screenFetch/pull/348

**Pull request closed without merging**
