### PR TITLE
Added AlterLinux logo

### PR DESCRIPTION
**Pull request by Hayao0819**
I have added the AlterLinux logo.
[AlterLinux](https://github.com/FascodeNet/alterlinux) is a derivative of ArchLinux developed in Japan.
The latest neofetch already has a logo added, but screenfetch did not.
I couldn't find a specific coding convention, but I wrote the code as much as possible, like any other.
I'm very excited and nervous about pulling requests for a large project. :)

### CODE REVIEW

**Comment by KittyKatt** [comment]
Hi, it looks like we have some conflicts with your merge. Could you try to fix some of those and verify that your branch is successfully detecting and outputting on AlterLinux?

**Comment by Hayao0819** [comment]
Sorry, I will fix it

**Comment by Hayao0819** [comment]
I have fixed.

**Comment by KittyKatt** [comment]
Merged!

**Comment by Hayao0819** [comment]
Thank you!

**Pull request merged**
