### PR TITLE
draugeros ditributive

### PR DESCRIPTION
**Pull request by sol4ik**

### CODE REVIEW

**Comment by KittyKatt** [comment]
Oof, that logo might be a bit too large. I might need to go back and remake it.

**Comment by Batcastle** [comment]
Yeah @KittyKatt that logo is a bit big. You are also getting a few errors in output. Attached is a screenshot of running on the current Alpha of Drauger OS
image

**Comment by Batcastle** [comment]
This might be a better size: https://pastebin.com/SyNB8Nyc

**Comment by Batcastle** [comment]
If I scale down the logo and fix the output bugs shown in the screenshot, then make a PR into @sol4ik 
's fork, would that help speed up getting this PR ready?

**Comment by KittyKatt** [comment]
That would help, yes. I haven't had time to work on anything recently.

**Pull request merged**
