### PR TITLE
Requesting a Merge of my changes into the upstream code branch

### PR DESCRIPTION
**Pull request by maxamillion**
Hi KittyKatt!

First, thanks for the script! It's quite good and I'm a fan as well as others in the irc circles I hang out in. I was hoping to get some more work done on sorting out the Gnome3/GTK3.x bits but I also don't want my changes to get too far out of band from the official repo.

I switched echo statements to printf as a side effect of the trampling POSIX specifications on it.

I also added some bits and changed some of the logic in places I felt it might be confusing for a newcomer to parse through. I also enforced 80 columns where possible and formatted in a more PEP8 style (but that's mostly preference). My changes are merely suggestions awaiting approval, feedback is highly welcomed!

I was hoping to merge the code together and then next official release I would package this up and maintain it for Fedora.

Many thanks!

-AdamM

### CODE REVIEW

**Comment by KittyKatt** [comment]
I'm finally gonna try to get this out of my PRs tomorrow by going over your commits and cherry picking what I like into current codebase.

**Comment by timofonic** [comment]
@KittyKatt Any news or we will have to wait for the stable GNU Hurd release? :D

PS: Forking hell and bored PRs are there...

**Comment by that4chanwolf** [comment]
Yeah I think kittykat isn't gonna be doing all that much any time soon.

**Comment by darealshinji** [comment]
@KittyKatt It's been open for 7 years now and a lot of parts in the script have been changed a lot. I think you should consider to close this one.

**Pull request closed without merging**
