### PR TITLE
add IP adress

### PR DESCRIPTION
**Pull request by xtuc**
I'm not a bash genius, the place where I edited the script is maybe not the best. Anyway, I added the IP address based on ipinfo.io API.

### CODE REVIEW

**Comment by darealshinji** [comment]
Can it be deactivated with a command?

**Comment by xtuc** [comment]
Yes it can, my code depends the detecthost() function.

**Comment by GLolol** [comment]
Does something like fetching the IP address of the local machine /really/ have to rely on a third party API?

**Comment by xtuc** [comment]
You can use `hostname -I`, but in my case I can't see my public IP adress as well as with `ipconfig`.

**Comment by GLolol** [comment]
Try `/sbin/ifconfig` or `ip addr show`.

**Comment by xtuc** [comment]
Both commands are showing me my private IP adress. I think the system can't know that way his public IP address because the router is protecting me.

**Comment by KittyKatt** [comment]
Not particularly keen on including this in sF. I'll think it over.

**Comment by cgoldberg** [comment]
@GLolol,

> Does something like fetching the IP address of the local machine /really/ have to rely on a third party API?

This PR isn't for "fetching the IP address of the local machine", it's to show the externally exposed IP.  Since most people access the internet behind a router, it is actually your router's IP address. (which is NAT'ed when your local machine makes TCP requests).  So yes, you need to rely on an external connection.  An easy way to do this is to make a network request through your router to a 3rd party service.

> Try /sbin/ifconfig or ip addr show

Neither of these will be helpful for getting the external IP address for reasons explained above.

**Comment by cgoldberg** [comment]
@xtuc ,

The request to retrieve the IP can be drastically simplified.

rather than:
`myIP=( $(curl -sS ipinfo.io | grep ip | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b") )`
you can just do:
`myIP=$(curl -s ipinfo.io/ip)`

There are many services that will echo back your external IP.  I'm not sure which is the best in terms of speed/reliability:

* curl -s checkip.amazonaws.com
* curl -s ipinfo.io/ip
* curl -s ipecho.net/plain
* curl -s ifconfig.me
* curl -s icanhazip.com
* curl -s ident.me

**Comment by GLolol** [comment]
@cgoldberg I understood that with @xtuc's later comments, since I originally had publicly facing servers in mind and not machines behind a NAT.

**Comment by xtuc** [comment]
Hi,

Te be honest, I don't care about my public IP anymore.
The local IP can still be helpfull (`hostname -I` for example).

Since you need to call an external service I think it's a bad idea to merge it into sF. As mentioned `curl ipinfo.io` works just fine.

**Pull request closed without merging**
