### PR TITLE
SteamOS support

### PR DESCRIPTION
**Pull request by darealshinji**
steamos
A Debian-based distribution.

### CODE REVIEW

**Comment by KittyKatt** [comment]
Lots of merge conflicts, so I'm gonna add this stuff in manually if that's okay with you.
.

**Comment by darealshinji** [comment]
Sure, I'm fine with that.

**Comment by darealshinji** [comment]
I guess in most cases the merge conflicts come from the `supported_distros=` line.

**Comment by darealshinji** [comment]
Merge conflict resolved. But you must add SteamOS to `supported_distros` manually.

**Pull request closed without merging**
