### PR TITLE
Add Fetched.io upload option.

### PR DESCRIPTION
**Pull request by justinseiter**
An upload option created to handle screenshots as well as screenfetch data.
http://fetched.io

### CODE REVIEW

**Comment by justinseiter** [comment]
If anyone would be willing to help me test out the web app, I would greatly appreciate it. I think I have  [fetched.io](http://fetched.io) at a pretty good spot for beta users and I desperately need to test against more distros. Until this pull is merged in you can use the committed code to update your local screenfetch copy. Thanks!

**Comment by KittyKatt** [comment]
Sorry, just getting around to PRs recently. I'm gonna look this over and possibly manually add it if you would still like me to.

**Comment by justinseiter** [comment]
I initially closed this request because I was relying too heavily on the "my..." options. I've since refactored. Also, after some testing I'm not 100% confident Fetched.io is ready. I'll be out of pocket soon until early 2016. So, I'm probably going to take down the site until I have the resources to support it. Sorry for the inconvenience.

**Comment by darealshinji** [comment]
I'm closing this. Re-open it or make a new pull request when Fetched.io is ready, okay?

**Pull request closed without merging**
