### PR TITLE
Update screenfetch-dev

### PR DESCRIPTION
**Pull request by parduscix**

### CODE REVIEW

**Comment by darealshinji** [comment]
> 1,304 additions, 2,831 deletions not shown because the diff is too large.
No, sorry. What exactly did you change?

**Comment by darealshinji** [comment]
I was taking a look at it and it seems you've added logo and detection for Pardus.
Can you show me the output of `lsb_release -sirc`, `cat /etc/os-release` and `cat /etc/pardus-release` please?

**Comment by parduscix** [comment]
/etc/pardus-release: DISTRIB_ID=PardusDISTRIB_RELEASE=4.0DISTRIB_CODENAME=ToplulukDISTRIB_DESCRIPTION="Pardus Topluluk 4.0 KDE" /etc/os-release: NAME="Pardus Topluluk"VERSION="4.0"ID=PardusID_LIKE=PTSPRETTY_NAME="Pardus"VERSION_ID="4.0"HOME_URL="http://portal.pardustopluluk.org/"SUPPORT_URL="http://portal.pardustopluluk.org/"BUG_REPORT_URL="http://portal.pardustopluluk.org/" 12.11.2016, 23:37, "darealshinji" <notifications@github.com>:Closed #412.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   ----- Ali Rıza KESKİN+905533459723Pardus Topluluk Mobil Platform Lideri

**Comment by parduscix** [comment]
lsb-release: DISTRIB_ID=PardusDISTRIB_RELEASE=4.0DISTRIB_CODENAME=ToplulukDISTRIB_DESCRIPTION="Pardus Topluluk 4.0 KDE" 13.11.2016, 08:54, "Ali Rıza KESKİN" <aliriza.keskin@pardustopluluk.org>:/etc/pardus-release: DISTRIB_ID=PardusDISTRIB_RELEASE=4.0DISTRIB_CODENAME=ToplulukDISTRIB_DESCRIPTION="Pardus Topluluk 4.0 KDE" /etc/os-release: NAME="Pardus Topluluk"VERSION="4.0"ID=PardusID_LIKE=PTSPRETTY_NAME="Pardus"VERSION_ID="4.0"HOME_URL="http://portal.pardustopluluk.org/"SUPPORT_URL="http://portal.pardustopluluk.org/"BUG_REPORT_URL="http://portal.pardustopluluk.org/" 12.11.2016, 23:37, "darealshinji" <notifications@github.com>:Closed #412.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   ----- Ali Rıza KESKİN+905533459723Pardus Topluluk Mobil Platform Lideri    ----- Ali Rıza KESKİN+905533459723Pardus Topluluk Mobil Platform Lideri

**Comment by dylanaraps** [comment]
I made some ascii art for Pardus.

```sh
 .smNdy+-    `.:/osyyso+:.`    -+ydmNs. 
/Md- -/ymMdmNNdhso/::/oshdNNmdMmy/. :dM/
mN.     oMdyy- -y          `-dMo     .Nm
.mN+`  sMy hN+ -:             yMs  `+Nm.
 `yMMddMs.dy `+`               sMddMMy` 
   +MMMo  .`  .                 oMMM+   
   `NM/    `````.`    `.`````    +MN`   
   yM+   `.-:yhomy    ymohy:-.`   +My   
   yM:          yo    oy          :My   
   +Ms         .N`    `N.      +h sM+   
   `MN      -   -::::::-   : :o:+`NM`   
    yM/    sh   -dMMMMd-   ho  +y+My    
    .dNhsohMh-//: /mm/ ://-yMyoshNd`    
      `-ommNMm+:/. oo ./:+mMNmmo:`      
     `/o+.-somNh- :yy: -hNmos-.+o/`     
    ./` .s/`s+sMdd+``+ddMs+s`/s. `/.    
        : -y.  -hNmddmNy.  .y- :        
         -+       `..`       +-         
```

**Comment by parduscix** [comment]
thank you 13.11.2016, 09:05, "Dylan Araps" <notifications@github.com>:I made some ascii art for Pardus. .smNdy+-    `.:/osyyso+:.`    -+ydmNs. 
/Md- -/ymMdmNNdhso/::/oshdNNmdMmy/. :dM/
mN.     oMdyy- -y          `-dMo     .Nm
.mN+`  sMy hN+ -:             yMs  `+Nm.
 `yMMddMs.dy `+`               sMddMMy` 
   +MMMo  .`  .                 oMMM+   
   `NM/    `````.`    `.`````    +MN`   
   yM+   `.-:yhomy    ymohy:-.`   +My   
   yM:          yo    oy          :My   
   +Ms         .N`    `N.      +h sM+   
   `MN      -   -::::::-   : :o:+`NM`   
    yM/    sh   -dMMMMd-   ho  +y+My    
    .dNhsohMh-//: /mm/ ://-yMyoshNd`    
      `-ommNMm+:/. oo ./:+mMNmmo:`      
     `/o+.-somNh- :yy: -hNmos-.+o/`     
    ./` .s/`s+sMdd+``+ddMs+s`/s. `/.    
        : -y.  -hNmddmNy.  .y- :        
         -+       `..`       +-         —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   ----- Ali Rıza KESKİN+905533459723Pardus Topluluk Mobil Platform Lideri

**Pull request closed without merging**
